export const CONNECTION_REQUEST_SUCCESS = 'CONNECTION_REQUEST_SUCCESS';
export const CONNECTION_REQUEST_ACCEPTED = 'CONNECTION_REQUEST_ACCEPTED';
export const CONNECTION_REQUEST_DECLINED = 'CONNECTION_REQUEST_DECLINED';
