export const CANCEL_LESSONS_FAILURE = 'CANCEL_LESSONS_FAILURE';
export const CANCEL_LESSONS_SUCCESS = 'CANCEL_LESSONS_SUCCESS';
export const CONNECTION_REQUEST_SUCCESS = 'CONNECTION_REQUEST_SUCCESS';
export const CONNECTION_REQUEST_ACCEPTED = 'CONNECTION_REQUEST_ACCEPTED';
export const CONNECTION_REQUEST_DECLINED = 'CONNECTION_REQUEST_DECLINED';
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS';
export const GET_LESSONS_FAILURE = 'GET_LESSONS_FAILURE';
export const LESSON_REQUEST_SUCCESS = 'LESSON_REQUEST_SUCCESS';
